### PR TITLE
Update TrueStatValues.toc

### PR DESCRIPTION
**Pull request by nanjuekaien1**

### CODE REVIEW

**Review by MSchiavi — APPROVED** [review]

**Comment by MSchiavi** [comment]
@nanjuekaien1 Going to merge this in and ill upload a new version of the addon tomorrow thanks!

**Comment by nanjuekaien1** [comment]
Some roles with the https://wago.io/bRl2gJIgz string installed will not display the Mastery attribute prompt. Anyone with feedback can ask if the string is installed first.

**Comment by MSchiavi** [comment]
> Some roles with the https://wago.io/bRl2gJIgz string installed will not display the Mastery attribute prompt. Anyone with feedback can ask if the string is installed first.

OK ill take a look thanks for bringing it up.

**Comment by nanjuekaien1** [comment]
https://github.com/mestar99/TrueCombatRatings/issues/2
This is the entirety of the platoon.
It started with exploring the Chinese forums about his Shaman not showing Mastery, I went and created a new level 60 trial account and found that it showed. In the end, he had no way to feedback, he went back to turn off all the plug-ins and found that it showed ‘精通: 增强元素’, and found that it was a string after checking.

**Pull request merged**
